version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo install pre build commands
      - npm install 
  build:
    commands:
      - echo Running tests
      - npm run build
      - echo building
  post_build:
    commands:
      - echo Entering Post_Build Phase, running node dist production files
      - node dist/index.js NODE_ENV=production
artifacts:
  files:
    - '**/*'