version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 14.x
  pre_build:
    commands:
      - echo install pre build commands

  build:
    commands:
      - echo Running tests
      - npm install && npm run build
      - echo building
  post_build:
    commands:
      - echo Entering Post_Build Phase
artifacts:
  files:
    - '**/*'